# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_extend_lang_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
